name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - uses: actions/checkout@v2
      - name: Build ROS Noetic Docker Image
        run: docker build -f Dockerfile_test_container . -t ros-noetic-simple-robotics
      # Run tests inside the container
      - name: Run tests in ROS Noetic container
        run: |
          docker run --rm ros-noetic-simple-robotics \
          /bin/bash -c "cd /root/ws/SimpleRoboticsPythonUtils && pytest"

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     cd SimpleRoboticsPythonUtils
      #     pip install .
      # - name: Run tests
      #   run: |
      #     cd SimpleRoboticsPythonUtils/tests  # Change to the correct directory
      #     pytest
